server:
  port: 8080

logging:
  config: file:D:\log4j2\log4j2.xml

spring:
  application:
    name: skych

  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

  messages:
    basename: i18n/common,i18n/swm
    encoding: UTF-8
    fallback-to-system-locale: false
    use-code-as-default-message: true #return code if true when not key-val found, or empty if false
    lang-default: en
    use-session: true #if true you can get locale lang by request.getSession().getAttribute("i18n-lang")
    lang-attribute-name: i18n-lang #the attribute name in http session if use session
    lang-param-name: lang #request.getAttribute(lang-param-name)

  redis:
    database: ${redis.database}
    host: ${redis.host}
    port: ${redis.port}
    lettuce:
      pool:
        min-idle: ${redis.pool.lettuce.min-idle}
        max-idle: ${redis.pool.lettuce.max-idle}
        max-active: ${redis.pool.lettuce.max-active}
        max-wait: ${redis.pool.lettuce.max-wait}

  datasource:
    driver-class-name: ${mysql.driver}
    url: ${mysql.url}
    username: ${mysql.username}
    password: ${mysql.password}
    type: ${datasource.type}
    hikari:
      minimum-idle: ${hikari.minimum-idle}
      maximum-pool-size: ${hikari.maximum-pool-size}
      idle-timeout: ${hikari.idle-timeout}
      pool-name: hikari-pool
      data-source-properties: #some mysql config properties suggested by HikariCP
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 1024
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false


mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: com.cloudminds.framework.mybatis.typehandler #add your handler package join by comma