server:
  port: 8080

spring:
  application:
    name: framework

  messages:
    basename: i18n/common,i18n/swm
    encoding: UTF-8
    fallback-to-system-locale: false
    use-code-as-default-message: true #return code if true when not key-val found, or empty if false
    defaultLang: en
    use-session: true #if true you can get locale lang by request.getSession().getAttribute("i18n-lang")
    lang-attribute-name: i18n-lang #the attribute name in http session if use session
    lang-param-name: lang #request.getAttribute(lang-param-name)



  redis:
    database: ${redis.database}
    host: ${redis.host}
    port: ${redis.port}
    lettuce:
      pool:
        min-idle: ${redis.pool.lettuce.min-idle}
        max-idle: ${redis.pool.lettuce.max-idle}
        max-active: ${redis.pool.lettuce.max-active}
        max-wait: ${redis.pool.lettuce.max-wait}